apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: advanced-cluster-management
  namespace: {{ .Values.namespace }}
  labels:
    demo.redhat.com/application: capacity-workshop
spec:
  channel: release-2.14
  installPlanApproval: Automatic
  name: advanced-cluster-management
  source: redhat-operators
  sourceNamespace: openshift-marketplace
